changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: API Changes
      labels:
        - 'api change'
    - title: Bug Fixes
      labels:
        - bug
    - title: Dependency Changes
      labels:
        - dependencies
