matrix:
  include:
    - os: linux
      dist: trusty
      language: android
      jdk: openjdk8
      env:
        - ADB_INSTALL_TIMEOUT=5
      android:
        components:
          - tools
          - platform-tools
          - build-tools-29.0.2
          - android-29
          - android-15
          - sys-img-armeabi-v7a-android-15
      before_install:
        - touch $HOME/.android/repositories.cfg
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
      before_script:
        - echo no | android create avd --force -n test -t android-15 --abi armeabi-v7a
        - emulator -avd test -no-skin -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
      deploy:
        provider: script
        script: ./gradlew extensions:threetenabp:publishAllPublicationsToMavenRepository
        skip_cleanup: true
        on:
          branch: master

    - os: osx
      osx_image: xcode10.2
      language: java
      install: ./gradlew core:assemble
      script: ./gradlew core:build
      deploy:
        provider: script
        script: ./gradlew core:publishAllPublicationsToMavenRepository
        skip_cleanup: true
        on:
          branch: master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/
    - $HOME/.android/build-cache
