name: Deploy website

on:
  release:
    types: [published]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install mkdocs
        run: pip3 install mkdocs mkdocs-material mkdocs-macros-plugin

      - name: Build documentation
        run: |
          ./gradlew generateMkdocsApiDocs
          mkdocs build

      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          SINGLE_COMMIT: true