name: Deploy website

on:
  release:
    types: [published]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install mkdocs
        run: pip install mkdocs-material mkdocs-macros-plugin

      - name: Build API docs
        run: ./gradlew dokkaMkdocs

      - name: Deploy
        run: mkdocs gh-deploy --force
