name: Test pull request

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Build and test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 21
          script: ./gradlew build connectedCheck
