name: Test and publish

on:
  push:
    branches:
      - master

jobs:
  macos-build:
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [21, 29]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew build connectedCheck

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD }}
        run: ./gradlew publishAllPublicationsToMavenRepository

env:
  ORG_GRADLE_PROJECT_iosDevice: "iPhone 11"